apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: app-credentials
  annotations:
    description: "Template to provision secrets for app environment"
    tags: "Orange,credentials"
    template.openshift.io/provider-display-name: "Mahali"
parameters:
  - name: APP_NAME
    description: Name to give for the provisioned service
    required: true
  - name: APP_TITLE
    description: Title of the webapp
    required: true
  - name: BASE_API_URL
    description: Mahali back-end API URL
    required: true
  - name: BASE_WEBAPP_URL
    description: Mahali webapp URL
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: ${APP_NAME}
    stringData:
      APP_TITLE: ${APP_TITLE}
      BASE_API_URL: ${BASE_API_URL}
      BASE_WEBAPP_URL: ${BASE_WEBAPP_URL}
    spec:
      parameters:
        APP_NAME: ${APP_NAME}
        APP_TITLE: ${APP_TITLE}
        BASE_API_URL: ${BASE_API_URL}
        BASE_WEBAPP_URL: ${BASE_WEBAPP_URL}
